In [2]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [4]:
first_aray = np.array(my_list)
print(first_aray)

[1 2 3]


In [7]:
D_List = [[1,2,3],[4,5,6],[7,8,9]]

second_array = np.array(D_List)

print(second_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#range is used to create a set of number betweem two numbers



A_3=np.arange(0,10,2)

print(A_3)

[0 2 4 6 8]


In [13]:
A_0 = np.zeros((5,5))

print(A_0)

A_1 = np.ones((3,5))

print(A_1)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
#Linspace used to divide the interval into specific no of points

LS_1 = np.linspace(0,10,50) 

print(LS_1)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [17]:
#identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#Random number

R_1 = np.random.rand(5) # creates a 1D array of 5 random numbers ranging between 0 and 1

print(R_1)

R_2 = np.random.rand(5,3,2) # 3D

print(R_2)

[0.29226763 0.12587126 0.35735296 0.49057701 0.56662184]
[[[0.2072542  0.61995485]
  [0.61914968 0.4457045 ]
  [0.94017038 0.12862073]]

 [[0.5197813  0.34079804]
  [0.48049929 0.46362614]
  [0.12435357 0.02310907]]

 [[0.26430837 0.86946289]
  [0.49987295 0.22138265]
  [0.98251865 0.95021558]]

 [[0.63700327 0.02019014]
  [0.97469384 0.39112652]
  [0.55230175 0.30601353]]

 [[0.81886505 0.29510656]
  [0.11191385 0.60541394]
  [0.75009294 0.30731093]]]


In [21]:
R_3_Gaussian = np.random.randn(3) # gives random number from the gaussian and std distribution

print(R_3_Gaussian)

[ 0.17875752 -1.10644566 -0.93656702]


In [23]:
arr_1 = np.arange(0,50)

print(arr_1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [25]:
ranarr_1 = np.random.randint(0,50,10)

print(ranarr_1)

[ 1 23 41 11 45 25 48 15 45 37]


In [30]:
# Reshaping array

R_A = arr_1.reshape(5,10)

print(R_A)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [33]:
max_R_A = R_A.max()
min_R_A = R_A.min()
index_R_A = R_A.argmax() # gives the index of maximum value


print(max_R_A, min_R_A, index_R_A)

49 0 49


In [40]:
print(arr_1.dtype)

arr_1.shape

int64


(50,)

In [3]:
arr_2 = np.arange(0,11)

print(arr_2)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
#slicing of array

arr_2[8]

8

In [8]:
arr_2[0:5]


array([0, 1, 2, 3, 4])

In [7]:
arr_2[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
# Broadcast

arr_2[0:2] = 100

print(arr_2)

[100 100   2   3   4   5   6   7   8   9  10]


In [12]:
arr_2_copy = arr_2.copy() # copy is used if you don't want to affect the parent array

arr_2_copy[0:2] = 1

print(arr_2)
print(arr_2_copy)

[100 100   2   3   4   5   6   7   8   9  10]
[ 1  1  2  3  4  5  6  7  8  9 10]


In [15]:


arr_2D = np.array([[1,2,2],[20,40,60],[3,6,9]])

print(arr_2D)

[[ 1  2  2]
 [20 40 60]
 [ 3  6  9]]


In [18]:
#2D Indexing

#double bracket format
print(arr_2D[0][0])

print(arr_2D[2][2])

1
9


In [19]:
#single bracket notation
print(arr_2D[2,2])

9


In [20]:
#Slicing rows and column
print(arr_2D[:2,1:]) #before the comma is row and after the comma is the column

[[ 2  2]
 [40 60]]


In [25]:
print(arr_2D[1:,:2])

[[20 40]
 [ 3  6]]


In [27]:
# Conditional selection

arr_3 = np.arange(1,11)
print(arr_3)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
bool_val_arr = arr_3 > 5

print(bool_val_arr)

[False False False False False  True  True  True  True  True]


In [29]:
arr_3[bool_val_arr]

array([ 6,  7,  8,  9, 10])

In [30]:
arr_3[arr_3 > 6]

array([ 7,  8,  9, 10])

In [32]:
#Home Practice 
arr_2d = np.arange(50).reshape(5 , 10)
print(arr_2d)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [37]:
print(arr_2d[2:4,1:4])

[[21 22 23]
 [31 32 33]]


In [38]:
# Numpy Operations

arr1 = np.arange(0,11)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [39]:
arr1 +2 #adds 2 to each element in the array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [40]:
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])